# Generated by Django 3.1.2 on 2020-10-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('businessID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='사업자 등록번호')),
                ('businessName', models.CharField(max_length=40, null=True, verbose_name='사업자명')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='사업자 이메일')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='사업자 이름')),
                ('phoneNum', models.CharField(max_length=30, null=True, verbose_name='사업자 전화번호')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='사업자 비밀번호')),
            ],
            options={
                'verbose_name': '사업자',
                'verbose_name_plural': '사업자',
                'db_table': 'Baker',
            },
        ),
        migrations.CreateModel(
            name='checkBaker',
            fields=[
                ('businessname', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='사업자명')),
                ('businessCRN', models.CharField(max_length=10, null=True, verbose_name='사업자 등록번호')),
            ],
            options={
                'verbose_name': '사업자 가입용',
                'verbose_name_plural': '사업자 가입용',
                'db_table': 'checkBaker',
            },
        ),
        migrations.CreateModel(
            name='checkOrderer',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문자 아이디')),
                ('useremail', models.EmailField(max_length=128, null=True, verbose_name='주문자 이메일')),
            ],
            options={
                'verbose_name': '주문자 가입용',
                'verbose_name_plural': '주문자 가입용',
                'db_table': 'checkOrderer',
            },
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('userID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문자 아이디')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='주문자 이메일')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='주문자 이름')),
                ('phoneNum', models.CharField(max_length=30, null=True, unique=True, verbose_name='주문자 전화번호')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='주문자 비밀번호')),
            ],
            options={
                'verbose_name': '주문자',
                'verbose_name_plural': '주문자',
                'db_table': 'Orderer',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('businessID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='사업자 등록번호')),
                ('storeName', models.CharField(max_length=30, null=True, verbose_name='가게 이름')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='가게 위치')),
                ('storeContact', models.CharField(max_length=30, null=True, unique=True, verbose_name='가게 연락처')),
                ('pickUpOpen', models.CharField(max_length=15, null=True, verbose_name='픽업 오픈 시간')),
                ('pickUpClose', models.CharField(max_length=15, null=True, verbose_name='픽업 마감 시간')),
                ('aboutStore', models.TextField(blank=True, null=True, verbose_name='가게 소개글')),
                ('storeImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='가게 대표이미지')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.baker')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.store')),
                ('cakeName', models.CharField(max_length=200, null=True, unique=True, verbose_name='케이크 이름')),
                ('cakeImg', models.ImageField(null=True, upload_to='', verbose_name='케이크 이미지')),
                ('cakePrice', models.IntegerField(null=True, verbose_name='1호 기준 가격')),
                ('mini', models.BooleanField(default=False, null=True, verbose_name='미니사이즈 가능 여부')),
            ],
            options={
                'verbose_name': '케이크',
                'verbose_name_plural': '케이크',
                'db_table': 'Cake',
            },
            bases=('home.store',),
        ),
        migrations.CreateModel(
            name='DetailedOption',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.store')),
                ('optionName', models.CharField(max_length=30, null=True, unique=True, verbose_name='옵션명')),
                ('isNecessary', models.BooleanField(default=False, null=True, verbose_name='필수 여부')),
                ('detailName', models.CharField(max_length=50, null=True, verbose_name='옵션 세부항목명')),
                ('pricing', models.IntegerField(null=True, verbose_name='추가 금액')),
                ('withColor', models.BooleanField(default=False, null=True, verbose_name='색상판 유무')),
                ('withImage', models.BooleanField(default=False, null=True, verbose_name='이미지추가 유무')),
            ],
            options={
                'verbose_name': '등록된 옵션',
                'verbose_name_plural': '등록된 옵션',
                'db_table': 'Options',
            },
            bases=('home.store',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('orderNum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('taste', models.IntegerField(null=True, verbose_name='맛 평점')),
                ('service', models.IntegerField(null=True, verbose_name='서비스 평점')),
                ('design', models.IntegerField(null=True, verbose_name='디자인 평점')),
                ('textReview', models.TextField(blank=True, null=True, verbose_name='한 줄 후기')),
                ('cakeStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.store')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderer')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNum', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('pickupDate', models.CharField(max_length=30, null=True, verbose_name='희망 수령일')),
                ('pickupTime', models.CharField(max_length=20, null=True, verbose_name='희망 픽업 시간')),
                ('businessID', models.CharField(max_length=50, null=True, verbose_name='사업자 등록번호')),
                ('cakeName', models.CharField(max_length=200, null=True, verbose_name='케이크 이름')),
                ('requiredOpt', models.TextField(null=True, verbose_name='필수 선택 옵션')),
                ('additionalOpt', models.TextField(blank=True, null=True, verbose_name='추가 선택 옵션')),
                ('cakeText', models.TextField(blank=True, null=True, verbose_name='케이크 문구')),
                ('message', models.TextField(blank=True, null=True, verbose_name='요청 사항')),
                ('price', models.IntegerField(null=True, verbose_name='가격')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='주문 진행 상황')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderer')),
            ],
            options={
                'verbose_name': '주문서',
                'verbose_name_plural': '주문서',
                'db_table': 'Order',
            },
        ),
    ]
