# Generated by Django 3.1.1 on 2020-11-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('userID', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='사업자 아이디')),
                ('businessID', models.CharField(max_length=10, null=True, verbose_name='사업자 등록번호')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='사업자 이메일')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='사업자 이름')),
                ('phoneNum', models.CharField(max_length=30, null=True, verbose_name='사업자 전화번호')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='사업자 비밀번호')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '사업자',
                'verbose_name_plural': '사업자',
                'db_table': 'Baker',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=50, null=True, verbose_name='사업자 등록번호')),
                ('cakeName', models.CharField(default='', max_length=200, verbose_name='케이크 이름')),
                ('cakeImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='케이크 이미지')),
                ('cakePrice', models.IntegerField(null=True, verbose_name='1호 기준 가격')),
                ('mini', models.CharField(choices=[('가능', '가능'), ('불가', '불가능')], default='', max_length=200, verbose_name='미니사이즈 가능 여부')),
            ],
            options={
                'verbose_name': '케이크',
                'verbose_name_plural': '케이크',
                'db_table': 'Cake',
            },
        ),
        migrations.CreateModel(
            name='checkBaker',
            fields=[
                ('userid', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='사업자 아이디')),
                ('businessCRN', models.CharField(max_length=10, null=True, verbose_name='사업자 등록번호')),
            ],
            options={
                'verbose_name': '사업자 가입용',
                'verbose_name_plural': '사업자 가입용',
                'db_table': 'checkBaker',
            },
        ),
        migrations.CreateModel(
            name='checkOrderer',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문자 아이디')),
                ('useremail', models.EmailField(max_length=128, null=True, verbose_name='주문자 이메일')),
            ],
            options={
                'verbose_name': '주문자 가입용',
                'verbose_name_plural': '주문자 가입용',
                'db_table': 'checkOrderer',
            },
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('userID', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='주문자 아이디')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='주문자 이메일')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='주문자 이름')),
                ('phoneNum', models.CharField(max_length=30, null=True, unique=True, verbose_name='주문자 전화번호')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='주문자 비밀번호')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '주문자',
                'verbose_name_plural': '주문자',
                'db_table': 'Orderer',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('businessID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='사업자 등록번호')),
                ('storeName', models.CharField(blank=True, max_length=30, null=True, verbose_name='가게 이름')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='가게 위치')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='가게 주소')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='가게 상세주소')),
                ('address3', models.CharField(blank=True, max_length=100, null=True, verbose_name='위치 추가정보')),
                ('daum_sido', models.CharField(blank=True, max_length=20, null=True, verbose_name='주문자와 비교할 시/도')),
                ('daum_sigungu', models.CharField(blank=True, max_length=20, null=True, verbose_name='주문자와 비교할 시/군/구')),
                ('daum_dong', models.CharField(blank=True, max_length=20, null=True, verbose_name='주문자와 비교할 읍/면/동')),
                ('storeContact', models.CharField(blank=True, max_length=30, null=True, verbose_name='가게 연락처')),
                ('pickUpOpen', models.CharField(blank=True, choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30')], max_length=15, null=True, verbose_name='픽업 오픈 시간')),
                ('pickUpClose', models.CharField(blank=True, choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30')], max_length=15, null=True, verbose_name='픽업 마감 시간')),
                ('aboutStore', models.TextField(blank=True, null=True, verbose_name='가게 소개글')),
                ('storeImg', models.ImageField(blank=True, default='logo_baker.png', null=True, upload_to='', verbose_name='가게 대표이미지')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.baker')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='DetailedOption',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.store')),
                ('optionName', models.CharField(max_length=30, null=True, unique=True, verbose_name='옵션명')),
                ('isNecessary', models.BooleanField(default=False, null=True, verbose_name='필수 여부')),
                ('withColor', models.BooleanField(default=False, null=True, verbose_name='색상판 유무')),
                ('withImage', models.BooleanField(default=False, null=True, verbose_name='이미지추가 유무')),
                ('detailName', models.CharField(max_length=50, null=True, verbose_name='옵션 세부항목명')),
                ('pricing', models.IntegerField(null=True, verbose_name='추가 금액')),
            ],
            options={
                'verbose_name': '등록된 옵션',
                'verbose_name_plural': '등록된 옵션',
                'db_table': 'Options',
            },
            bases=('home.store',),
        ),
        migrations.CreateModel(
            name='openDays',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.store')),
                ('monday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='월요일 주문가능 수량')),
                ('tuesday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='화요일 주문가능 수량')),
                ('wednesday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='수요일 주문가능 수량')),
                ('thursday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='목요일 주문가능 수량')),
                ('friday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='금요일 주문가능 수량')),
                ('saturday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='토요일 주문가능 수량')),
                ('sunday', models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='일요일 주문가능 수량')),
            ],
            options={
                'verbose_name': '주문가능 수량',
                'verbose_name_plural': '주문가능 수량',
                'db_table': 'openDays',
            },
            bases=('home.store',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('orderNum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('taste', models.IntegerField(null=True, verbose_name='맛 평점')),
                ('service', models.IntegerField(null=True, verbose_name='서비스 평점')),
                ('design', models.IntegerField(null=True, verbose_name='디자인 평점')),
                ('textReview', models.TextField(blank=True, null=True, verbose_name='한 줄 후기')),
                ('cakeStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.store')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderer')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNum', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('pickupDate', models.CharField(max_length=30, null=True, verbose_name='희망 수령일')),
                ('pickupTime', models.CharField(max_length=20, null=True, verbose_name='희망 픽업 시간')),
                ('businessID', models.CharField(max_length=50, null=True, verbose_name='사업자 등록번호')),
                ('cakeName', models.CharField(max_length=200, null=True, verbose_name='케이크 이름')),
                ('requiredOpt', models.TextField(null=True, verbose_name='필수 선택 옵션')),
                ('additionalOpt', models.TextField(blank=True, null=True, verbose_name='추가 선택 옵션')),
                ('cakeText', models.TextField(blank=True, null=True, verbose_name='케이크 문구')),
                ('message', models.TextField(blank=True, null=True, verbose_name='요청 사항')),
                ('price', models.IntegerField(null=True, verbose_name='가격')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='주문 진행 상황')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderer')),
            ],
            options={
                'verbose_name': '주문서',
                'verbose_name_plural': '주문서',
                'db_table': 'Order',
            },
        ),
    ]
