# Generated by Django 3.1.1 on 2020-11-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지 이름'),
        ),
    ]
